#!/usr/bin/env python3
"""Wire the collected quotes (quotes.json) into the graph.

Two outputs, both idempotent and run after wiki_compile:
1. A managed `<!-- quote-links -->` index block in the `knowledge base quotes`
   page note, grouping every quote under the [[nodes]] it touches.
2. A managed `<!-- quotes -->` block inside each connected *curated* node
   (concepts / people / works / life / sources) holding the verbatim quotes that
   belong to that idea — so a quote about death lives inside [[Amor Fati]] itself.

Book and artist nodes are regenerated by other tools, so quotes that connect to
those appear only in the page index (embedding there would be overwritten).

Matching reuses the knowledge-base matchers plus a prose-tuned keyword layer.
Every emitted [[target]] is verified to resolve; the lint stays at zero broken.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

from wiki_knowledge_base import (
    CONCEPT_KW, compile_kw, people_matcher, book_matcher, artist_matcher,
    known_targets, classify, safe_text,
)

VAULT = Path(__file__).resolve().parents[1]
WIKI = VAULT / "knowledge" / "wiki"
PAGES = WIKI / "pages"
QUOTES_JSON = Path("/Users/erneststrauhal/GitHub/strauh.al4/quotes.json")
NOTE = PAGES / "knowledge base quotes.md"

# Folders whose notes are NOT regenerated, so an embedded block survives a refresh.
SAFE_DIRS = ["concepts", "people", "works", "life", "sources"]
PER_NODE_EMBED = 25
PER_NODE_INDEX = 40

IDX_START, IDX_END = "<!-- quote-links:start -->", "<!-- quote-links:end -->"
Q_START, Q_END = "<!-- quotes:start -->", "<!-- quotes:end -->"

EXTRA: dict[str, list[str]] = {
    "Spontaneity and Elegance": ["painting", "paint", "brush", "beginner", "expert", "simplicity", "effortless", "elegant", "spontaneous", "improvis*"],
    "Art Fills the God-Shaped Hole": ["beauty", "beautiful", "sublime", "soul", "sacred", "transcend*", "divine", "worship", "faith", "prayer"],
    "Amor Fati": ["death", "die", "dying", "mortality", "fate", "suffering", "meaning", "nietzsche", "eternal", "tragedy"],
    "The Oedipal Screen": ["desire", "mother", "father", "gaze", "hysteria", "unconscious", "dream"],
    "AI Slop": ["machine", "artificial", "automat*", "algorithm", "generated"],
    "Latent Space": ["machine", "neural", "deleuze", "interpolat*", "vector"],
    "Memory and Preservation": ["memory", "remember", "forget", "the past", "ancient", "nostalg*", "preserve"],
    "The Attention Economy": ["attention", "distraction", "boredom", "bored", "scroll", "feed"],
    "The Tedium of the Art Is the Goal": ["practice", "repetition", "discipline", "mastery", "expert", "tedium", "patience", "labor", "labour"],
    "Transmitting My Neural Signals by Hand": ["by hand", "gesture", "draw*", "painting", "mark-making", "penmanship", "calligraph*", "handwriting"],
    "The Internet as Confidant": ["internet", "online", "the web"],
    "Atomization": ["alone", "lonel*", "isolation", "alienat*", "fisher"],
    "Post-Irony": ["irony", "ironic", "sincerity", "sincere"],
    "Reading Like a Computer": ["reading", "read a book", "attention span"],
    "Human-Machine Tug of War": ["machine", "tool", "control", "collaborat*"],
    "Dead Architecture": ["ruin", "architecture", "decay"],
    "Synesthesia": ["color", "colour", "sound", "music"],
}


def merged_matchers():
    merged = {c: list(CONCEPT_KW.get(c, [])) + EXTRA.get(c, []) for c in set(CONCEPT_KW) | set(EXTRA)}
    return {c: compile_kw(kws) for c, kws in merged.items()}


def clean(quote: str) -> str:
    q = re.sub(r"[ \t]+", " ", html.unescape(quote).strip())
    # neutralize stray wiki/markdown link syntax so embedding can't forge links
    return q.replace("[[", "[").replace("]]", "]")


def truncate(q: str) -> str:
    q = re.sub(r"\s+", " ", q).strip('"').strip()
    return safe_text(q if len(q) <= 90 else q[:88].rstrip() + "…")


def blockquote(q: str) -> str:
    lines = [ln.rstrip() for ln in q.split("\n")]
    return "\n".join((f"> {ln}" if ln else ">") for ln in lines)


def append_block_bottom(path: Path, block: str, start: str, end: str) -> bool:
    """Remove any existing block, then append it at the very bottom of the note."""
    text = path.read_text()
    pat = re.compile(r"\n*" + re.escape(start) + r".*?" + re.escape(end) + r"\n*", re.S)
    new = pat.sub("\n", text).rstrip() + "\n\n" + block + "\n"
    if new != text:
        path.write_text(new)
        return True
    return False


def insert_block(path: Path, block: str, start: str, end: str) -> bool:
    text = path.read_text()
    pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if pat.search(text):
        text2 = pat.sub("\x00B\x00", text)
        text2 = text2.replace("\x00B\x00", block, 1).replace("\x00B\x00", "")
        new = re.sub(r"\n{3,}", "\n\n", text2)
    else:
        for anchor in ("<!-- archive-links:start -->", "<!-- vault-crosslinks:start -->"):
            if anchor in text:
                new = text.replace(anchor, block + "\n\n" + anchor, 1)
                break
        else:
            new = text.rstrip() + "\n\n" + block + "\n"
    if new != text:
        path.write_text(new)
        return True
    return False


def render_index(groups: dict, total: int, connected: int) -> str:
    lines = [IDX_START, "## Connections", "",
             f"*Each quote wired to the ideas, people, and books it touches — "
             f"{connected} of {total} quotes connected ({len(groups)} nodes). The full "
             f"text of each lives inside the node it connects to.*", ""]
    for node in sorted(groups, key=lambda n: (-len(groups[n]), n)):
        items = groups[node][:PER_NODE_INDEX]
        extra = f" …+{len(groups[node]) - len(items)} more" if len(groups[node]) > len(items) else ""
        qs = " · ".join(f'"{truncate(q)}"' for q in items)
        lines += [f"**[[{node}]]** — {qs}{extra}", ""]
    lines.append(IDX_END)
    return "\n".join(lines)


def render_quotes(quotes: list, node: str) -> str:
    seen, uniq = set(), []
    for q in quotes:
        k = q.strip().lower()
        if k not in seen:
            seen.add(k)
            uniq.append(q)
    shown = uniq[:PER_NODE_EMBED]
    extra = (f"\n\n*…and {len(uniq) - len(shown)} more on [[knowledge base quotes]].*"
             if len(uniq) > len(shown) else "")
    body = "\n>\n".join(blockquote(q) for q in shown)
    return (f"{Q_START}\n## Quotes\n\n"
            f"*Collected quotes that speak to this — see all on "
            f"[[knowledge base quotes]].*\n\n{body}{extra}\n{Q_END}")


def safe_node_files():
    files = {}
    for d in SAFE_DIRS:
        for p in (WIKI / d).glob("*.md"):
            t = p.read_text(errors="ignore")
            m = re.search(r"^title:\s*(.+)$", t, re.M)
            title = (m.group(1).strip().strip('"') if m else p.stem)
            files[title] = p
            files.setdefault(p.stem, p)
    return files


def main():
    if not QUOTES_JSON.exists() or not NOTE.exists():
        print("quotes.json or quotes note missing; skipping.")
        return
    quotes = json.loads(QUOTES_JSON.read_text())
    known = known_targets()
    M = merged_matchers()
    people, books, artists = people_matcher(), book_matcher(), artist_matcher()

    groups: dict[str, list] = {}
    connected = 0
    for item in quotes:
        raw = item.get("quote", "")
        if not raw.strip():
            continue
        nodes = classify(raw, "", M, people, books, artists, known)
        if nodes:
            connected += 1
        for n in nodes:
            groups.setdefault(n, []).append(clean(raw))

    if not groups:
        print("No quote connections found.")
        return

    insert_block(NOTE, render_index(groups, len(quotes), connected), IDX_START, IDX_END)

    node_files = safe_node_files()
    embedded = 0
    for node, qs in groups.items():
        path = node_files.get(node)
        if path and append_block_bottom(path, render_quotes(qs, node), Q_START, Q_END):
            embedded += 1

    total_links = sum(len(v) for v in groups.values())
    print(f"Quotes wired: {connected}/{len(quotes)} connected, {len(groups)} nodes, "
          f"{total_links} links; verbatim quotes embedded in {embedded} curated nodes.")


if __name__ == "__main__":
    main()
